server:
  port: 8080

spring:
  mail:
    username: s.jamshididana@gmail.com
    to: Lisa
    host: smtp.gmail.com
    port: 587
    password: necljgwvbhtibtuu
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            required: true
            enable: true

visualcrossing:
  api:
    key: TNRLU3LFMM54H3TQLA6E5P4QC